// This file was generated by counterfeiter
package fake

import (
	"sync"

	"github.com/xchapter7x/chaospeddler/service_broker"
)

type FakeOrchestrator struct {
	StartStub        func()
	startMutex       sync.RWMutex
	startArgsForCall []struct{}
}

func (fake *FakeOrchestrator) Start() {
	fake.startMutex.Lock()
	fake.startArgsForCall = append(fake.startArgsForCall, struct{}{})
	fake.startMutex.Unlock()
	if fake.StartStub != nil {
		fake.StartStub()
	}
}

func (fake *FakeOrchestrator) StartCallCount() int {
	fake.startMutex.RLock()
	defer fake.startMutex.RUnlock()
	return len(fake.startArgsForCall)
}

var _ chaospeddler.Orchestrator = new(FakeOrchestrator)
